import { Database as DB } from '../../../src/types/database'; // Assuming you have a separate database.ts or this is a consolidated file

// --- Frontend-facing User and Listing Interfaces (CamelCase) ---
export interface User {
  id: string;
  name: string;
  email: string;
  university: string;
  year: string;
  bio: string;
  profilePicture?: string;
  verified: boolean;
  student_verified?: boolean;
  student_email?: string;
  verification_status?: 'unverified' | 'pending' | 'verified' | 'rejected';
  verification_method?: string;
  verified_at?: Date;
  createdAt: Date;
  phone?: string;
  preferences?: {
    smokingAllowed: boolean;
    petsAllowed: boolean;
    studyFriendly: boolean;
    socialLevel: 'quiet' | 'moderate' | 'social';
    maxBudget?: number;
    preferredRoomTypes?: string[];
    preferredAmenities?: string[];
  };
  location?: {
    address: string;
    city: string;
    state: string;
    country: string;
    coordinates?: {
      lat: number;
      lng: number;
    };
  };
  matchingPreferences?: { // This is camelCase for the frontend User interface
    maxDistance: number; // in miles
    sameUniversity: boolean;
    similarYear: boolean;
    budgetRange: {
      min: number;
      max: number;
    };
  };
}

export interface Listing {
  id: string;
  title: string;
  description: string;
  price: number;
  location: {
    address: string;
    city: string;
    state: string;
    country: string;
    latitude: number;
    longitude: number;
    nearbyUniversities: { name: string; distance: number }[];
  };
  roomType: 'single' | 'shared' | 'studio' | 'apartment';
  amenities: string[];
  images: string[];
  availableFrom: Date;
  availableTo?: Date;
  maxOccupants: number;
  hostId: string;
  host: User;
  createdAt: Date;
  updatedAt: Date;
  status: 'active' | 'inactive' | 'rented';
  preferences: {
    gender?: 'male' | 'female' | 'any';
    smokingAllowed: boolean;
    petsAllowed: boolean;
    studyFriendly: boolean;
    ageRange?: {
      min: number;
      max: number;
    };
    yearPreference?: string[];
  };
  rules?: string[];
  deposit?: number;
  utilities?: {
    included: boolean;
    cost?: number;
  };
  matchScore?: number; // Calculated based on user preferences
  relevanceScore?: number; // Based on location, university, etc.
}

export interface SearchFilters {
  query?: string;
  location?: string;
  university?: string | { custom: string };
  maxDistance?: number;
  priceRange?: { min?: number; max?: number };
  roomType?: string[];
  amenities?: string[];
  moveInDate?: string;
  availableFrom?: Date;
  sortBy?: 'relevance' | 'price' | 'date';
}

export interface Message {
  id: string;
  senderId: string;
  receiverId: string;
  listingId: string;
  content: string;
  timestamp: Date;
  read: boolean;
  type: 'text' | 'image' | 'system';
}

export interface Conversation {
  id: string;
  participants: User[];
  listing: Listing;
  messages: Message[];
  lastMessage: Message;
  updatedAt: Date;
  unreadCount: number;
}

export interface MatchingCriteria {
  university: string;
  location: {
    city: string;
    state: string;
    coordinates?: {
      lat: number;
      lng: number;
    };
  };
  maxDistance: number;
  budgetRange: {
    min: number;
    max: number;
  };
  preferences: {
    roomTypes: string[];
    amenities: string[];
    lifestyle: {
      smokingAllowed: boolean;
      petsAllowed: boolean;
      studyFriendly: boolean;
      socialLevel: 'quiet' | 'moderate' | 'social';
    };
  };
}

export interface Notification {
  id: string;
  userId: string;
  type: 'message' | 'listing_inquiry' | 'listing_update' | 'system' | 'new_match';
  title: string;
  message: string;
  read: boolean;
  createdAt: Date;
  actionUrl?: string;
  metadata?: any;
}

export interface UniversityData {
  id: string;
  name: string;
  city: string;
  state: string;
  country: string;
  coordinates: {
    lat: number;
    lng: number;
  };
  studentCount: number;
  popularAreas: string[];
  averageRent: {
    single: number;
    shared: number;
    studio: number;
    apartment: number;
  };
}

// --- Supabase Database Schema Types (Snake_Case for columns) ---
// Note: If you have a separate `src/types/database.ts` file generated by Supabase,
// it's usually better to import that. For now, I'm modifying the definition
// as it was provided embedded here.
export interface Database {
  public: {
    Tables: {
      profiles: {
        Row: {
          id: string;
          name: string;
          university: string;
          year: string;
          bio: string;
          phone: string | null;
          verified: boolean;
          student_verified: boolean | null;
          student_email: string | null;
          verification_status: 'unverified' | 'pending' | 'verified' | 'rejected' | null;
          verification_method: string | null;
          verified_at: string | null;
          profile_picture: string | null;
          preferences: any; // jsonb
          created_at: string;
          updated_at: string;
          email?: string | null;
          location: any | null;
          matching_preferences: any | null; // FIXED: Changed from matchingPreferences to matching_preferences
        };
        Insert: {
          id: string;
          name: string;
          university: string;
          year: string;
          bio?: string;
          phone?: string | null;
          verified?: boolean;
          student_verified?: boolean | null;
          student_email?: string | null;
          verification_status?: 'unverified' | 'pending' | 'verified' | 'rejected' | null;
          verification_method?: string | null;
          verified_at?: string | null;
          profile_picture?: string | null;
          preferences?: any;
          created_at?: string;
          updated_at?: string;
          email?: string | null;
          location?: any | null;
          matching_preferences?: any | null; // FIXED: Changed from matchingPreferences to matching_preferences
        };
        Update: {
          id?: string;
          name?: string;
          university?: string;
          year?: string;
          bio?: string;
          phone?: string | null;
          verified?: boolean;
          student_verified?: boolean | null;
          student_email?: string | null;
          verification_status?: 'unverified' | 'pending' | 'verified' | 'rejected' | null;
          verification_method?: string | null;
          verified_at?: string | null;
          profile_picture?: string | null;
          preferences?: any;
          created_at?: string;
          updated_at?: string;
          email?: string | null;
          location?: any | null;
          matching_preferences?: any | null; // FIXED: Changed from matchingPreferences to matching_preferences
        };
      };
      listings: {
        Row: {
          id: string;
          title: string;
          description: string;
          price: number;
          location: any; // jsonb
          room_type: 'single' | 'shared' | 'studio' | 'apartment';
          amenities: string[];
          images: string[];
          available_from: string;
          available_to: string | null;
          max_occupants: number;
          host_id: string;
          status: 'active' | 'inactive' | 'rented';
          preferences: any; // jsonb
          rules: string[];
          deposit: number | null;
          utilities: any; // jsonb
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          title: string;
          description: string;
          price: number;
          location: any;
          room_type: 'single' | 'shared' | 'studio' | 'apartment';
          amenities?: string[];
          images?: string[];
          available_from: string;
          available_to?: string | null;
          max_occupants?: number;
          host_id: string;
          status?: 'active' | 'inactive' | 'rented';
          preferences?: any;
          rules?: string[];
          deposit?: number | null;
          utilities?: any;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          title?: string;
          description?: string;
          price?: number;
          location?: any;
          room_type?: 'single' | 'shared' | 'studio' | 'apartment';
          amenities?: string[];
          images?: string[];
          available_from?: string;
          available_to?: string | null;
          max_occupants?: number;
          host_id?: string;
          status?: 'active' | 'inactive' | 'rented';
          preferences?: any;
          rules?: string[];
          deposit?: number | null;
          utilities?: any;
          created_at?: string;
          updated_at?: string;
        };
      };
      conversations: {
        Row: {
          id: string;
          listing_id: string;
          participant_1: string;
          participant_2: string;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          listing_id: string;
          participant_1: string;
          participant_2: string;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          listing_id?: string;
          participant_1?: string;
          participant_2?: string;
          created_at?: string;
          updated_at?: string;
        };
      };
      messages: {
        Row: {
          id: string;
          conversation_id: string;
          sender_id: string;
          content: string;
          message_type: 'text' | 'image' | 'system';
          read: boolean;
          created_at: string;
        };
        Insert: {
          id?: string;
          conversation_id: string;
          sender_id: string;
          content: string;
          message_type?: 'text' | 'image' | 'system';
          read?: boolean;
          created_at?: string;
        };
        Update: {
          id?: string;
          conversation_id?: string;
          sender_id?: string;
          content?: string;
          message_type?: 'text' | 'image' | 'system';
          read?: boolean;
          created_at?: string;
        };
      };
      favorites: {
        Row: {
          id: string;
          user_id: string;
          listing_id: string;
          created_at: string;
        };
        Insert: {
          id?: string;
          user_id: string;
          listing_id: string;
          created_at?: string;
        };
        Update: {
          id?: string;
          user_id?: string;
          listing_id?: string;
          created_at?: string;
        };
      };
    };
  };
}